import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { ArrowRight, ChevronLeft, MessageCircle, Search, X } from "lucide-react";

type Stock = { size: string; quantity: number };
type ChatMessage = { role: "user" | "assistant"; content: string };
type Product = { product_id: string; name: string; garment_type: string; description: string; colors: string[]; search_tags: string[]; image_url: string; price: number; inventory: Stock[] };
const API = import.meta.env.VITE_API_URL || "http://127.0.0.1:8015";
const money = (price: number) => `$${price.toFixed(2)}`;
const image = (p: Product) => `${API}${p.image_url}`;

export function App() {
  const [products, setProducts] = useState<Product[]>([]);
  const [path, setPath] = useState(window.location.pathname);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [sort, setSort] = useState("featured");
  const [chatOpen, setChatOpen] = useState(false);
  const [chatMessage, setChatMessage] = useState("");
  const [chatReply, setChatReply] = useState("Hi! Ask me about products, prices, sizes, or stock.");
  const [chatBusy, setChatBusy] = useState(false);
  const [chatProducts, setChatProducts] = useState<Product[]>([]);
  const [chatSearchDone, setChatSearchDone] = useState(false);
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);
  const [auth, setAuth] = useState<"login" | "register" | null>(null);
  const [sessionToken, setSessionToken] = useState(() => localStorage.getItem("campus_session"));
  useEffect(() => { fetch(`${API}/api/products`).then(r => r.json()).then(setProducts).catch(() => setProducts([])); }, []);
  useEffect(() => { if (!sessionToken) return; fetch(`${API}/api/chat/history`, { headers: { "X-Session-Token": sessionToken } }).then(r => r.ok ? r.json() : []).then((history: ChatMessage[]) => { setChatHistory(history); const last = [...history].reverse().find(item => item.role === "assistant"); if (last) setChatReply(last.content); }).catch(() => undefined); }, [sessionToken]);
  useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, []);
  const navigate = (to: string) => { window.history.pushState({}, "", to); setPath(to); window.scrollTo(0, 0); };
  const filtered = useMemo(() => { const result = products.filter(p => (category === "all" || p.garment_type === category) && `${p.name} ${p.garment_type} ${p.search_tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())); return [...result].sort((a, b) => sort === "price-low" ? a.price - b.price : sort === "price-high" ? b.price - a.price : a.name.localeCompare(b.name)); }, [products, query, category, sort]);
  const detail = path.startsWith("/products/") ? products.find(p => p.product_id === decodeURIComponent(path.split("/")[2])) : undefined;
  return <div className="app">
    <header className="nav"><button className="brand" onClick={() => navigate("/")}><span className="brand-mark">CC</span><span>Campus <em>Customs</em></span></button><nav><button onClick={() => navigate("/")}>Home</button><button onClick={() => navigate("/products")}>Products</button><button onClick={() => navigate("/about")}>About Us</button></nav><div className="nav-actions"><button className="text-button" onClick={() => setAuth("login")}>Log in</button><button className="nav-cta" onClick={() => setAuth("register")}>Create account</button></div></header>
    {detail ? <Detail product={detail} back={() => navigate("/products")} /> : path === "/about" ? <About /> : path === "/products" ? <Products products={filtered} allProducts={products} query={query} setQuery={setQuery} category={category} setCategory={setCategory} sort={sort} setSort={setSort} open={navigate} /> : <Home products={products.slice(0, 4)} open={navigate} />}
    <footer><span>© 2026 Campus Customs</span><span>Made for the Yale community</span></footer>
    <button className="chat-fab" onClick={() => setChatOpen(!chatOpen)} aria-label="Open chat"><MessageCircle size={22} /></button>
    {chatSearchDone && <section className="section chat-results"><div className="section-heading"><div><p className="eyebrow">FROM YOUR SEARCH</p><h2>{chatProducts.length ? "Here’s what we found." : "No products matched."}</h2></div></div>{chatProducts.length > 0 ? <div className="product-grid">{chatProducts.map(p => <Card key={p.product_id} product={p} open={navigate}/>)}</div> : <p className="muted">Try a different category, color, or product name.</p>}</section>}
    {chatOpen && <ChatPanel history={chatHistory} message={chatMessage} setMessage={setChatMessage} reply={chatReply} busy={chatBusy} send={async () => { if (!chatMessage.trim() || chatBusy) return; const message = chatMessage.trim(); setChatMessage(""); setChatBusy(true); const headers: Record<string, string> = { "Content-Type": "application/json" }; if (sessionToken) headers["X-Session-Token"] = sessionToken; try { const r = await fetch(`${API}/api/chat`, { method: "POST", headers, body: JSON.stringify({ message, conversation: chatHistory, current_page: path, product_id: detail?.product_id || null }) }); const body = await r.json(); if (r.ok) { setChatReply(body.message); setChatHistory(prev => [...prev, { role: "user", content: message }, { role: "assistant", content: body.message }]); setChatProducts((body.suggested_products || []).map((p: Product) => ({ ...p, colors: p.colors || [], search_tags: p.search_tags || [], inventory: p.inventory || [] }))); setChatSearchDone(true); } else { setChatReply(body.detail || "The concierge is unavailable right now."); setChatProducts([]); setChatSearchDone(true); } } catch { setChatReply("The concierge is unavailable right now."); setChatProducts([]); setChatSearchDone(true); } finally { setChatBusy(false); } }} close={() => setChatOpen(false)} />}
    {auth && <AuthModal mode={auth} close={() => setAuth(null)} />}
  </div>;
}

function ChatPanel({ history, message, setMessage, reply, busy, send, close }: { history: ChatMessage[]; message: string; setMessage: (value: string) => void; reply: string; busy: boolean; send: () => void; close: () => void }) { return <div className="chat"><div className="chat-head"><div><strong>Campus Customs Concierge</strong><small>Powered by PydanticAI</small></div><button onClick={close}><X size={18}/></button></div><div className="chat-body">{history.length ? history.map((item, index) => <div className={`bubble ${item.role}`} key={`${item.role}-${index}`}>{item.content}</div>) : <div className="bubble">{busy ? "Checking the collection…" : reply}</div>}{busy && <div className="bubble">Checking the collection…</div>}</div><form className="chat-input" onSubmit={e => { e.preventDefault(); send(); }}><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Ask about our collection" /><button type="submit" disabled={busy}><ArrowRight size={18}/></button></form></div> }

function AuthModal({ mode, close }: { mode: "login" | "register"; close: () => void }) { const [form, setForm] = useState({ first_name: "", last_name: "", email: "", password: "" }); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); setMessage(""); setBusy(true); try { const r = await fetch(`${API}/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await r.json(); if (!r.ok) throw new Error(body.detail || "Something went wrong."); localStorage.setItem("campus_session", body.session_token); document.cookie = `campus_session=${body.session_token}; path=/`; setMessage(body.message); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Something went wrong."); } finally { setBusy(false); } }; return <div className="modal-backdrop" onClick={close}><div className="auth-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={close}><X size={18}/></button><p className="eyebrow">CAMPUS CUSTOMS</p><h2>{mode === "login" ? "Welcome back." : "Join the community."}</h2><p className="muted">{mode === "login" ? "Sign in to continue your Campus Customs journey." : "Create an account for a more personal shop experience."}</p><form onSubmit={submit}>{mode === "register" && <div className="form-row"><input required placeholder="First name" value={form.first_name} onChange={e => setForm({...form, first_name: e.target.value})}/><input required placeholder="Last name" value={form.last_name} onChange={e => setForm({...form, last_name: e.target.value})}/></div>}<input required type="email" placeholder="Email address" value={form.email} onChange={e => setForm({...form, email: e.target.value})}/><input required minLength={mode === "register" ? 8 : 1} type="password" placeholder="Password" value={form.password} onChange={e => setForm({...form, password: e.target.value})}/><button className="primary wide" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Log in" : "Create account"}</button></form>{message && <p className="auth-message">{message}</p>}<button className="switch-auth" onClick={() => { setMessage(""); setForm({ first_name: "", last_name: "", email: "", password: "" }); }}>{mode === "login" ? "Need an account? Create one" : "Already have an account? Log in"}</button></div></div> }

function Home({ products, open }: { products: Product[]; open: (p: string) => void }) { return <><section className="hero"><div className="hero-copy"><p className="eyebrow">THE YALE COMMUNITY COLLECTION</p><h1>Wear your<br/><i>belonging.</i></h1><p className="hero-text">Thoughtful pieces for the people, places, and traditions that make campus feel like home.</p><button className="primary" onClick={() => open("/products")}>Shop the collection <ArrowRight size={18}/></button></div><div className="hero-card"><span>NEW ARRIVALS</span><div className="hero-circle">CC</div><strong>Built for<br/>the bold.</strong></div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">FRESH FROM CAMPUS</p><h2>Find your favorite.</h2></div><button className="link-button" onClick={() => open("/products")}>View all products <ArrowRight size={16}/></button></div><div className="product-grid">{products.map(p => <Card key={p.product_id} product={p} open={open}/>)}</div></section></> }
function Products({ products, allProducts, query, setQuery, category, setCategory, sort, setSort, open }: { products: Product[]; allProducts: Product[]; query: string; setQuery: (v: string) => void; category: string; setCategory: (v: string) => void; sort: string; setSort: (v: string) => void; open: (p: string) => void }) { const categories = [...new Set(allProducts.map(p => p.garment_type))].sort(); return <main className="section products-page"><div className="section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>All products</h2><p className="muted">Real campus staples, ready for wherever your day takes you.</p></div><label className="search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search the collection" /></label></div><div className="filters"><select value={category} onChange={e => setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(item => <option key={item} value={item}>{item}</option>)}</select><select value={sort} onChange={e => setSort(e.target.value)}><option value="featured">Sort: A–Z</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select><span className="muted">{products.length} products</span></div><div className="product-grid">{products.map(p => <Card key={p.product_id} product={p} open={open}/>)}{!products.length && <p className="muted">No products found.</p>}</div></main> }
function Card({ product, open }: { product: Product; open: (p: string) => void }) { return <article className="card" onClick={() => open(`/products/${encodeURIComponent(product.product_id)}`)}><div className="card-image"><img src={image(product)} alt={product.name}/><span>{product.garment_type}</span></div><div className="card-info"><div><h3>{product.name}</h3><p>{product.description}</p></div><strong>{money(product.price)}</strong></div></article> }
function Detail({ product, back }: { product: Product; back: () => void }) { const available = product.inventory.filter(s => s.quantity > 0); return <main className="detail"><button className="back" onClick={back}><ChevronLeft size={17}/> Back to products</button><div className="detail-layout"><div className="detail-image"><img src={image(product)} alt={product.name}/></div><div className="detail-copy"><p className="eyebrow">{product.garment_type}</p><h1>{product.name}</h1><div className="price">{money(product.price)}</div><p className="detail-description">{product.description}</p><div className="rule"/><h4>Available colors</h4><p>{product.colors.join(" · ")}</p><h4>Sizes & stock</h4><div className="sizes">{product.inventory.map(s => <span className={s.quantity === 0 ? "sold" : ""} key={s.size}>{s.size} <small>{s.quantity ? `${s.quantity} left` : "Sold out"}</small></span>)}</div>{!available.length && <p className="sold-message">This item is currently out of stock.</p>}<button className="primary wide">Add to bag <ArrowRight size={18}/></button></div></div></main> }
function About() { return <main className="about"><p className="eyebrow">OUR STORY</p><h1>Good things<br/><i>start here.</i></h1><div className="about-columns"><p>Campus Customs is a small collection built around the feeling of finding your people. We make everyday pieces with enough character for a quad walk, a late-night library run, and every story in between.</p><p>Our point of view is simple: campus style should feel personal, durable, and unmistakably yours. Explore the collection, find a favorite, and make it part of your day.</p></div><div className="about-band"><span>YALE BLUE,</span><strong>EVERYDAY ENERGY.</strong></div></main> }
